
version: '3'

services:
  api:
    build:
      context: ./ScholarScraperBE
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./ScholarScraperFE
    ports:
      - "4200:4200"

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=scholarscraperdb
      - POSTGRES_PASSWORD=ouiouibonjour

  selenium-hub:
    image: selenium/standalone-chrome:3.4.0
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 4444:4444
