
version: '3'

services:
  api:
    container_name: scholarscraperbe
    build: ./ScholarScraperBE
    ports:
      - "8000:8000"

  frontend:
    container_name: scholarscraperfe
    build: ./ScholarScraperFE
    ports:
      - "4200:4200"
