
version: '3'

services:
  api:
    build:
      context: ./ScholarScraperBE
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./ScholarScraperFE
    depends_on:
      - api
    ports:
      - "4200:4200"

  scraper:
    build:
      context: ./ScholarScraper 
    deploy:
      restart_policy:
        condition: any
        delay: 1d
        max_attempts: 3
        window: 120s
