INSERT INTO `google`.`scholar`
VALUES (SYSDATE(), 'wvvIyOwAAAAJ', 'Eyuphan Bulut', true),
    (SYSDATE(), '8f_w4HQAAAAJ', 'Alberto Cano', true),
    (SYSDATE(), 'hrWVmoAAAAAJ', 'Krzysztof J Cios', true),
    (SYSDATE(), 'M5W9tuUAAAAJ', 'Thang N. Dinh', true),
    (SYSDATE(), '3f847ugAAAAJ', 'Kostadin Damevski', true),
    (SYSDATE(), 'lIYpkGYAAAAJ', 'Carol Fung', true),
    (SYSDATE(), 'S30uT7YAAAAJ', 'preetam ghosh', true),
    (SYSDATE(), '2TOvEFoAAAAJ', 'Vojislav Kecman', true),
    (SYSDATE(), '0GrFcZsAAAAJ', 'Bartosz Krawczyk', true),
    (SYSDATE(), 'zXw_54AAAAAJ', 'Lukasz Kurgan', true),
    (SYSDATE(), 'thmq-GAAAAAJ', 'John D. Leonard II', true),
    (SYSDATE(), 'jp-Ye7gAAAAJ', 'Milos Manic', true),
    (SYSDATE(), 'dWRneN0AAAAJ', 'Bridget T. McInnes', true),
    (SYSDATE(), '0ltdcO4AAAAJ', 'Tamer Nadeem', true),
    (SYSDATE(), 'dVbCvDtnltMC', 'Cang Ye', true),
    (SYSDATE(), 'SJ8Ssp4AAAAJ', 'Tarynn M Whitten', true),
    (SYSDATE(), 'PQl5OHMAAAAJ', 'Hong-Sheng Zhou', true);