
FROM python:3.7

# Install python dependencies
RUN pip3 install pipenv

WORKDIR /usr/src/app

COPY Pipfile ./

RUN set -ex && pipenv install --deploy --system

COPY . .

# I'll start the server later
CMD [ "gunicorn", "-b0.0.0.0:$PORT", "src.main:app" ]


