
# Stage One

# install base image
FROM node as node

# set working directory
RUN mkdir /usr/src/app

WORKDIR /usr/src/app

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /usr/src/app/package.json

RUN npm install
RUN npm install -g @angular/cli

# add app
COPY . .

# ng build
RUN ng build

CMD ng serve

# Stage 2
# FROM nginx:1.13.12-alpine

# COPY --from=node /usr/src/app/dist/* /usr/share/nginx/html/

# COPY ./nginx.conf /etc/nginx/conf.d/default.conf

# CMD sed -i -e 's/$PORT/'"$PORT"'/g' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'
